2024-02-13T07:36:47 {"cpu": 0.1328125, "cpu_total": 8, "cpu_usage": 0.0166015625, "memory": 900.0, "memory_total": 3997.0, "memory_usage": 0.22516887665749313, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707809807.089797, "uuid": "196ec8efca914330bd8d08f3a80b05b3"}
2024-02-13T07:36:47 {"cpu": 0.1328125, "cpu_total": 8, "cpu_usage": 0.0166015625, "memory": 938.0, "memory_total": 3997.0, "memory_usage": 0.23467600700525393, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707809807.313698, "uuid": "2e8c2f3af4214dae92f26d06cf030b4e"}
2024-02-13T07:36:47 {"block_run_id": 1, "block_uuid": "green_taxi_data_loader", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline green_taxi_etl block green_taxi_data_loader", "timestamp": 1707809807.36951, "uuid": "6af764fc818f435caa8845a6ad6bb727"}
2024-02-13T07:36:56 {"cpu": 0.1640625, "cpu_total": 8, "cpu_usage": 0.0205078125, "memory": 1266.0, "memory_total": 3997.0, "memory_usage": 0.3167375531648737, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707809816.667691, "uuid": "1b9805bf781947f1a6b54a0139f2d606"}
2024-02-13T07:36:57 {"block_run_id": 1, "block_uuid": "green_taxi_data_loader", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "BlockRun 1 (block_uuid: green_taxi_data_loader) completes.", "timestamp": 1707809817.403713, "uuid": "120335e0835c4edeb81448ebd251a3f1"}
2024-02-13T07:37:06 {"cpu": 0.17919921875, "cpu_total": 8, "cpu_usage": 0.02239990234375, "memory": 1060.0, "memory_total": 3997.0, "memory_usage": 0.2651988991743808, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707809826.900392, "uuid": "573ab4c5944b4d7ebea8f72f0146835b"}
2024-02-13T07:37:07 {"block_run_id": 2, "block_uuid": "transform_green_taxi_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 2: pipeline green_taxi_etl block transform_green_taxi_data", "timestamp": 1707809827.139769, "uuid": "1a268c2c6d464fbaae9f54645be5ce24"}
2024-02-13T07:37:08 {"block_run_id": 2, "block_uuid": "transform_green_taxi_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "BlockRun 2 (block_uuid: transform_green_taxi_data) completes.", "timestamp": 1707809828.010365, "uuid": "7a208d3ba84440b3bfe1b9a26595b451"}
2024-02-13T07:37:16 {"cpu": 0.25830078125, "cpu_total": 8, "cpu_usage": 0.03228759765625, "memory": 1056.0, "memory_total": 3997.0, "memory_usage": 0.26419814861145857, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707809836.151992, "uuid": "41b3480f31ef4b25919dc28ab77d7469"}
2024-02-13T07:37:16 {"block_run_id": 3, "block_uuid": "export_green_taxi_data_to_postgres", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 3: pipeline green_taxi_etl block export_green_taxi_data_to_postgres", "timestamp": 1707809836.350666, "uuid": "6fbe600235af456394ed3b7afbaf9c86"}
2024-02-13T07:37:16 {"block_run_id": 3, "block_uuid": "export_green_taxi_data_to_postgres", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "EXCEPTION", "message": "BlockRun 3 (block_uuid: export_green_taxi_data_to_postgres) failed.", "timestamp": 1707809836.773846, "uuid": "7dd64ae03c384e0aacaeacf27266edb7", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 345, in conn\n    return self._ctx\nAttributeError: 'Postgres' object has no attribute '_ctx'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 605, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 578, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1052, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1285, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1194, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1509, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1665, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1704, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 359, in export\n    __process()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 292, in __process\n    table_exists = self.table_exists(schema_name, table_name)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py\", line 166, in table_exists\n    with self.conn.cursor() as cur:\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 347, in conn\n    raise ConnectionError(\nConnectionError: No connection currently open. Open a new connection to access this property.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1580, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 107, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 173, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 275, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 240, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["No connection currently open. Open a new connection to access this property."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 345, in conn
    return self._ctx
AttributeError: 'Postgres' object has no attribute '_ctx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 605, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 578, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1052, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1285, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1194, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1509, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1665, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1704, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 359, in export
    __process()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 292, in __process
    table_exists = self.table_exists(schema_name, table_name)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py", line 166, in table_exists
    with self.conn.cursor() as cur:
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 347, in conn
    raise ConnectionError(
ConnectionError: No connection currently open. Open a new connection to access this property.
2024-02-13T07:37:17 {"block_run_id": 4, "block_uuid": "export_green_taxi_data_to_gcs", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 4: pipeline green_taxi_etl block export_green_taxi_data_to_gcs", "timestamp": 1707809837.36472, "uuid": "c8b6c023253741d7894536520fbc2160"}
2024-02-13T07:37:21 {"block_run_id": 4, "block_uuid": "export_green_taxi_data_to_gcs", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "BlockRun 4 (block_uuid: export_green_taxi_data_to_gcs) completes.", "timestamp": 1707809841.502877, "uuid": "a7b34efee91a49bf8ed550ecde91a4b4"}
2024-02-13T07:37:26 {"cpu": 0.283203125, "cpu_total": 8, "cpu_usage": 0.035400390625, "memory": 1072.0, "memory_total": 3997.0, "memory_usage": 0.2682011508631474, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "9e633581b7bd", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707809846.455279, "uuid": "81465623c29b492f9f8918640a9d1e84"}
